default_config:
  mode: KEEP

# tables:
#   - table_name_with_schema: "public.staff"
#     transformations:
#       - columns:
#           - "first_name"
#         params:
          

schema_creation_mode: CREATE_IF_NOT_EXISTS
safety_mode: "RELAXED"
table_truncation_mode: TRUNCATE
