name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Number generated entries / 10
        # Otherwise it is impossible to execute it on GHA runner
        run: |
          sed -i.bak -E 's/(: +[1-9](0|_)+)0/\1/g' config.yaml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-testinfra

      - name: Build docker-compose
        run: |
          docker-compose pull
          docker-compose build

      - name: Run the workflow
        run: |
          docker-compose run tdk

      - name: Debug
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker-compose ps
          docker-compose exec output_db bash -c "psql -U postgres -t -c 'SELECT COUNT(*) FROM address'"

      - name: Verify results
        shell: 'script -q -e -c "bash {0}"'
        run: py.test -v test_tdk.py
